version: '3.9'

services:
  cassandra-seed-dc1-rack1-node1:
    build:
      context: .
      args:
        CASSANDRA_VERSION: "${CASSANDRA_VERSION}"
    networks:
      cassandra-net:
        ipv4_address: 172.29.0.2
    expose:
      - "9042"
      - "7199"
      - "8778"
      - "7000"
      - "7001"
      - "8443"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-node-dc1-rack1-node2,cassandra-node-dc2-rack1-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=${MAX_HEAP_SIZE:-3G}
      - HEAP_NEWSIZE=${HEAP_NEWSIZE:-400M}
      - LOCAL_JMX=no
      - JOLOKIA=${JOLOKIA}
      - PEM_ENABLED=${PEM_ENABLED}
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote.authenticate=false -Dcassandra.superuser_setup_delay_ms=0 -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.ring_delay_ms=0
    volumes:
      - cassandra-seed-dc1-rack1-node1-data:/var/lib/cassandra
      - ./cassandra-rackdc-dc1-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ${CERTIFICATE_DIRECTORY}:/etc/certificates

  cassandra-seed-dc2-rack1-node1:
    build:
      context: .
      args:
        CASSANDRA_VERSION: "${CASSANDRA_VERSION}"
    networks:
      cassandra-net:
        ipv4_address: 172.29.0.3
    expose:
      - "9042"
      - "7199"
      - "8778"
      - "7000"
      - "7001"
      - "8443"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=datacenter2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-node-dc1-rack1-node2,cassandra-node-dc2-rack1-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=${MAX_HEAP_SIZE:-3G}
      - HEAP_NEWSIZE=${HEAP_NEWSIZE:-400M}
      - LOCAL_JMX=no
      - JOLOKIA=${JOLOKIA}
      - PEM_ENABLED=${PEM_ENABLED}
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote.authenticate=false -Dcassandra.superuser_setup_delay_ms=0 -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.ring_delay_ms=0
    volumes:
      - cassandra-seed-dc2-rack1-node1-data:/var/lib/cassandra
      - ./cassandra-rackdc-dc2-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ${CERTIFICATE_DIRECTORY}:/etc/certificates

  cassandra-node-dc1-rack1-node2:
    build:
      context: .
      args:
        CASSANDRA_VERSION: "${CASSANDRA_VERSION}"
    networks:
      cassandra-net:
        ipv4_address: 172.29.0.4
    expose:
      - "9042"
      - "7199"
      - "8778"
      - "7000"
      - "7001"
      - "8443"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-node-dc1-rack1-node2,cassandra-node-dc2-rack1-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=${MAX_HEAP_SIZE:-3G}
      - HEAP_NEWSIZE=${HEAP_NEWSIZE:-400M}
      - LOCAL_JMX=no
      - JOLOKIA=${JOLOKIA}
      - PEM_ENABLED=${PEM_ENABLED}
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote.authenticate=false -Dcassandra.superuser_setup_delay_ms=0 -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.ring_delay_ms=0
    volumes:
      - cassandra-node-dc1-rack1-node2-data:/var/lib/cassandra
      - ./cassandra-rackdc-dc1-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ${CERTIFICATE_DIRECTORY}:/etc/certificates

  cassandra-node-dc2-rack1-node2:
    build:
      context: .
      args:
        CASSANDRA_VERSION: "${CASSANDRA_VERSION}"
    networks:
      cassandra-net:
        ipv4_address: 172.29.0.5
    expose:
      - "9042"
      - "7199"
      - "8778"
      - "7000"
      - "7001"
      - "8443"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=datacenter2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-seed-dc1-rack1-node1,cassandra-seed-dc2-rack1-node1,cassandra-node-dc1-rack1-node2,cassandra-node-dc2-rack1-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=${MAX_HEAP_SIZE:-3G}
      - HEAP_NEWSIZE=${HEAP_NEWSIZE:-400M}
      - LOCAL_JMX=no
      - JOLOKIA=${JOLOKIA}
      - PEM_ENABLED=${PEM_ENABLED}
      - JVM_EXTRA_OPTS=-Dcom.sun.management.jmxremote.authenticate=false -Dcassandra.superuser_setup_delay_ms=0 -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.ring_delay_ms=0
    volumes:
      - cassandra-node-dc2-rack1-node2-data:/var/lib/cassandra
      - ./cassandra-rackdc-dc2-rack1.properties:/etc/cassandra/cassandra-rackdc.properties
      - ${CERTIFICATE_DIRECTORY}:/etc/certificates

volumes:
  cassandra-seed-dc1-rack1-node1-data:
  cassandra-seed-dc2-rack1-node1-data:
  cassandra-node-dc1-rack1-node2-data:
  cassandra-node-dc2-rack1-node2-data:

networks:
  cassandra-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
